### ISSUE TITLE
[BUG] - Plugin upgrade from v1 to v2

### ISSUE THREAD

**Issue by kidmis** [vultr/terraform-provider-vultr#120]
**Describe the bug**
Seems there is no automatic way to convert state files during plugin updrade from v1 plugin to v2. Could you clarify what is the correct way for this? 

**To Reproduce**
1. set `version = ">= 2.1.3"` in required_providers directive
2. do "terraform init"
3. do "terraform plan"
4. getting lots of errors regarding invalid resource type (due to syntax changes)
5. change manifest (.tf) files to new syntax
6. do `terraform plan`
7. getting errors - Provider configuration not present

**Expected behavior**
tfstate files converting to new scheme 

**Screenshots**
https://i.imgur.com/Xi3RoWf.png
https://i.imgur.com/HY9q0Ai.png

**Desktop (please complete the following information where applicable:**
 - OS: Ubuntu 20.04.1 LTS (5.4.0-42-generic)
 - Terraform version: v0.13.6
 - source provider registry.terraform.io/-/vultr v1.3.3
 - target provider registry.terraform.io/vultr/vultr v2.1.3

**Additional context**

**Comment by ddymko** [comment]
@kidmis There is no way to automatically convert v1 to v2.

There are a lot of changes from v1 to v2 and this is due to the Vultr API changing from v1 to v2 
https://github.com/vultr/terraform-provider-vultr/blob/master/example/V2Changes.md

This would be a manually process of updating your `.tf` file and `import`ing all of your existing resources. You could do this in the existing `.tf` or create a new a new one where you are just importing all of your existing resources.
