### ISSUE TITLE
[Feature] - Allow Private Network to attach to Instances, like Block Storage, instead of vultr_instance private_network_ids

### ISSUE THREAD

**Issue by grant-veepshosting** [vultr/terraform-provider-vultr#133]
**Is your feature request related to a problem? Please describe.**
Building a Terraform module, and private networks are optional and only used in some specific use cases. When building the "Compute" (Vultr Instance) portion of the module, it's not currently easily possible to have -
1. Optional Data Lookup (this MUST have a value, doesn't work for Optional resources):
data "vultr_private_network" "my_network" {
  filter {
    name = "description"
    values = ["my-network-description"]
  }
}

2. Have the value explicitly set to Null or "fall back" to Null doesn't work, Errors with:
private_network_ids = [tostring(try(var.private_network_ids, null))]
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 26, in resource "vultr_instance" "server":
│   26:   private_network_ids    = tostring(try(var.private_network_ids, null))
│     ├────────────────
│     │ var.private_network_ids is "null"
│ 
│ Inappropriate value for attribute "private_network_ids": list of string
│ required.

OR

      + private_network_ids    = [
          + "null",
        ]
(validates OK in Terraform plan), yet the API returns:
Error: error creating server: {"error":"Invalid UUID format.","status":400}

**Describe the solution you'd like**
Similar to the way the way the vultr_block_storage attached_to_instance parameter works, likely with a for_each loop for each attachment, this way the vultr_private_network resource can do the vultr_instance resource ID lookip instead.

**Describe alternatives you've considered**
1. Getting optional data source lookup to work, likely using a "count" solution
2. Using Parent-Child module relationships with an output parameter for the Private Network ID
3. Passing in private_network_ids manually as a list from variables
None of these alternatives deliver the goal of building the private network with Terraform code then attaching automatically to one or more instances, whilst retaining the private network as Optional.

**Comment by ddymko** [comment]
@grant-veepshosting 

Just going to go over everything in order

> private_network_ids = [tostring(try(var.private_network_ids, null))]

This will turn `null` into `"null"` and then add it to the array which will give you with what you have below.

> + private_network_ids    = [
      + "null",
    ]


This will fail as you are passing in a string of null as an element to the array. If you want to pass in a truely nil value it would have to be `[]` or `private_network_ids = []`. Go will read this as private_network_ids is nil and not process anything.

```hcl
resource "vultr_instance" "main" {
  plan             = "vc2-1c-1gb"
  region           = "sea"
  os_id            = 167
  label = "value"
  private_network_ids = []
}
```

This will run and build with no private networks being attached and allows it to remain optional.

 > Similar to the way the way the vultr_block_storage attached_to_instance parameter works

We can't have this within Terraform for private_networks as it would cause drift.

For `block_storage` since the API allows attaching instances on block storage. The instance doesn't have any fields  that say it is mounted to a block. Block storage contains that information.

With `private_networks` this is the opposite. We take the `private_network` ID and apply that to 1 to N instances. If we were to introduce the behavior of passing `instance ids` to `private_networks` then instance resources TF would notice a change in the state file from what you have defined in your `.tf` file. This would cause drift and terraform would detach those `private_networks`

Note: While digging into this I noticed that instances aren't getting `private_network_ids` updated in their statefile so that needs to be fixed.

**Comment by grant-veepshosting** [comment]
Thanks for the feedback on this @ddymko. We are still facing some challenges with this, namely even with manual dependency satisfaction (build a private network using tf, use the network .id as an output variable as input for the compute module), we are seeing "var.private_network_ids is empty tuple" "Inappropriate value for attribute "private_network_ids": element 0: string required.". Trying to define the variable with a default of either [] or null to cover both use cases (server with or without a private network) is still proving challenging.

**Comment by ddymko** [comment]
@grant-veepshosting could you give us the .tf file you have defined? This will make it easier for us to dig into this for you

**Comment by grant-veepshosting** [comment]
@ddymko of course, thanks very much - your input is deeply appreciated.
https://github.com/Veeps-Hosting/terraform-terragrunt-vultr/blob/main/compute/vars.tf
https://github.com/Veeps-Hosting/terraform-terragrunt-vultr/blob/main/compute/main.tf

**Comment by ddymko** [comment]
Thanks for sharing - I'll try to dig into this for you sometime this week.

**Comment by grant-veepshosting** [comment]
Thanks - please prefer Release 1.2 as we're still developing on the Master branch. Release 1.2 is the closest we had it to both working for 1 scenario, and not for the other, reliably.

**Comment by Oogy** [comment]
@grant-veepshosting looking at the `v1.2` code its not clear to me why this would not satisfy both cases of an instance being created with and without a private network. If the variable contains a populated list, the instance is attached to the listed networks. If the argument is not used, and left with the default of `[]` it will be ignored and the instance will not attach to any networks.

Could you please share some specific input values you've used with `v1.2` that are leading to issues? Also please share any relevant command output/errors.

**Comment by grant-veepshosting** [comment]
Thanks for looking into this @Oogy.
Given the original request isn't technically possible (or at least, advisable), I'll close this for now and raise a new Issue with succinct steps to reproduce in the next couple of days.
