### ISSUE TITLE
Don't detach networks when destroying a server

### ISSUE THREAD

**Issue by devicenull** [vultr/terraform-provider-vultr#16]
https://github.com/terraform-providers/terraform-provider-vultr/blob/b8a6cb7add72061abcb59627067d748896a7fe0c/vultr/resource_vultr_server.go#L597

Destroying a server should automatically detach any private networks that were attached.  Doing this before destroying just slows everything down.

**Comment by ddymko** [comment]
@devicenull 

Previously we had an issue where through the API we had intermittent issues where the networks would not detach on destroy so we put this in place to mitigate that.

I'll take some time to test and verify that issue is no longer happening.

**Comment by johnrichardrinehart** [comment]
@devicenull It seems that the code you linked does exactly what you want (namely, automatically detaches any private networks that were attached), but maybe I'm misunderstanding what "[disable](https://github.com/hashicorp/terraform-provider-vultr/blob/b8a6cb7add72061abcb59627067d748896a7fe0c/vendor/github.com/vultr/govultr/server.go#L525)` means, in this context.

@ddymko It seems that this method is [still](https://github.com/hashicorp/terraform-provider-vultr/blob/master/vultr/resource_vultr_server.go#L610) using the [`/v1` API](https://github.com/hashicorp/terraform-provider-vultr/blob/master/vendor/github.com/vultr/govultr/server.go#L525) to do this instead of the newer [`detach`](https://www.vultr.com/api/#operation/detach-instance-network) API method.

Would you accept a PR to upgrade the `govultr` to use the `/v2` API? If so, I can file an issue over [at that repo](https://github.com/vultr/govultr/issues).

**Comment by ddymko** [comment]
@johnrichardrinehart you are looking at an old archived repo.

This is for the current TF provider
https://github.com/vultr/terraform-provider-vultr/blob/master/vultr/resource_vultr_instance.go#L444

The reason we have the detach prior to deletion is to prevent a race condition on TF if you are trying to also delete the private network that it is attached to.

To avoid any issues like this we detach on TF.

**Comment by johnrichardrinehart** [comment]
Ah, yeah, I didn't notice it was the Hashicorp repo.

It seems to me that @devicenull wants exactly what's already being done, which is to detach a private network when a server is being deleted (similar to ISOs being detached on ISO deletion).

But, maybe that's why you closed the issue.
