### ISSUE TITLE
Unable to create `vultr_firewall_rule`.

### ISSUE THREAD

**Issue by rossigee** [vultr/terraform-provider-vultr#2]
Using provider version 1.0.5...

```
$ terraform providers -v | grep vultr
+ provider.vultr v1.0.5
```

Referring to docs page here: https://www.terraform.io/docs/providers/vultr/r/firewall_rule.html#from_port

Example HCL:

```
resource "vultr_firewall_rule" "http" {
  firewall_group_id = vultr_firewall_group.cluster.id
  network        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 80
  to_port           = 80
  notes             = "http"
}
```

On `terraform apply`...

```
Error: Err creating firewall group : Unable to add rule: Invalid port number - must be between 1 and 65535

  on modules/vultr/firewall.tf line 15, in resource "vultr_firewall_rule" "http":
  15: resource "vultr_firewall_rule" "http" {

```

Which port number is invalid? The `from_port` or the `to_port`? Both are set to 80, which is between 1 and 65535.

**Comment by ddymko** [comment]
@rossigee 

Thanks creating the ticket. The behavior you are running into to is a side effect of the Vultr V1 API. If you are trying to define a single port opening, in your example port 80, then you just need to define the `from_port`.

```hcl
resource "vultr_firewall_rule" "http" {
  firewall_group_id = vultr_firewall_group.cluster.id
  network        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 80
  notes             = "http"
}
```

If however you would want to open open ports 80 to 85 then you would define your `from_port` (80) and your `to_port` (85) 

```hcl
resource "vultr_firewall_rule" "http" {
  firewall_group_id = vultr_firewall_group.cluster.id
  network        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 80
  to_port           = 85
  notes             = "http"
}
```

So in your instance since you are just defining a single port of 80 you only need to define the `from_port`. I'll take note of this as the docs do not explain this clearly which is a bit confusing and update it so it is more clear.

Hopefully this helps!

**Comment by rossigee** [comment]
Thanks, @ddymko.

As suggested, commenting out the `to_port` allows these rules to apply as expected.

**Comment by rossigee** [comment]
As well as documenting this quirk (or instead of), perhaps worth adding some code along the lines of 'if to_port equals from_port, only send from_port to API V1'.

**Comment by ddymko** [comment]
@rossigee 

I will create a new ticket to add an enhancement like that!
