### ISSUE TITLE
[Feature] - Allow Instances to be updated with new IP reservation

### ISSUE THREAD

**Issue by tomasbasham** [vultr/terraform-provider-vultr#270]
**Is your feature request related to a problem? Please describe.**

I am currently unable to assign a previously reserved IP address to a running instance without it needing to be recreated. This seems quite unnecessary whilst I am able to do exactly what I require through the Vultr web UI. It seems the issue however is more related to the Vultr API rather than the provider exclusively and must first be implemented there.

**Describe the solution you'd like**

I would like the `ForceReplacement` flag removed from the `reserved_ip_id` field of the Vultr instance resource and for the API to allow me to attach a reserved IP to a running instance.

**Comment by optik-aper** [comment]
Thanks for the request.  I don't see any reason why it is set to force replacement so I'll test it out and fix this for the next release.

**Comment by optik-aper** [comment]
@tomasbasham After some review, I see the rationale of what's going on with the reserved IPs.  The [instance routes](https://www.vultr.com/api/#tag/instances) currently don't allow an update to `reserved_ip` after creation.  That said, there is a resource for the reserved IPs so perhaps you can do what you want using it.  For example:
```
resource "vultr_instance" "inst-i" {
  plan = "vc2-1c-2gb"
  region = "ams"
  os_id = 244
  label = "tf-i"
}

resource "vultr_reserved_ip" "rip-i" {
  region = "ams"
  ip_type = "v4"
  instance_id = vultr_instance.inst-i.id
}
```

Then if you want to create a new reserved IP and attach it like:
```
resource "vultr_instance" "inst-i" {
  plan = "vc2-1c-2gb"
  region = "ams"
  os_id = 244
  label = "tf-i"
}

resource "vultr_reserved_ip" "rip-i" {
  region = "ams"
  ip_type = "v4"
}

resource "vultr_reserved_ip" "rip-ii" {
  region = "ams"
  ip_type = "v4"
  instance_id = vultr_instance.inst-i.id
}
```
The only issue I can see with this is that, in order to pick up the new reserved IP, the instance has to be rebooted after switching to the new reserved IP.  We will investigate (as time allows) building that functionality into the `reserved_ip` resource similar to how we do it with the [instance_ipv4](https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/instance_ipv4) resource.

**Comment by tomasbasham** [comment]
Ah I had not noticed you can set the VPS instance on the reserved IP resource itself. If that is the case then that may solve my issue. Thanks

**Comment by optik-aper** [comment]
No problem!
