### ISSUE TITLE
Once an instance is created, it's not possible to detach the ISO

### ISSUE THREAD

**Issue by marrold** [vultr/terraform-provider-vultr#36]
I created a `vultr_server` with and `iso_id` defined however now the OS has been installed it's not possible to detach the ISO.

I have removed the `iso_id` from the resource but when I apply there are no actions and the ISO remains attached. 

Thanks

**Comment by ddymko** [comment]
Hey @marrold 

This is correct the ISO remains attached and due to the manual process of ISOs there is no easy way for us to know when your ISO has finished installing for us to deatch it. 

You could either detach the ISO manually or create instances with a snapshot. If this is a custom ISO you have that you are using you may want to look into using packer which allows you to create a snapshot.
