### ISSUE TITLE
Inconsistent Terraform state when hitting rate limit

### ISSUE THREAD

**Issue by SamWhited** [vultr/terraform-provider-vultr#44]
If you add several DNS records to your Terraform config and apply, you will fairly quickly hit the rate limit and the apply will be canceled. However, afterwards if try to apply again you will get errors because the resources have already been created on Vultr, but not saved to the Terraform config. Because you can't import DNS records to my knowledge, the only recourse is to go in and manually remove several dozen new DNS records.

**Comment by ddymko** [comment]
The current ratelimit on the API is less then ideal (3 r/s). One thing we have in place to alleviate the pain points with the V1 rate limit is letting you adjust the rate calls are sent and how many times a call should retry.

https://www.terraform.io/docs/providers/vultr/index.html#example-usage

Like stated in #42 we are overhauling the entire API in V2 which will also offer a more usable rate limit.

**Comment by SamWhited** [comment]
This isn't a problem with the API, this is a problem with the Terraform plugin (although better rate limiting would be nice too :) ). Regardless of how good the rate limit is, at some point it may be possible to hit it. When this happens, the apply does not save the already applied Terraform state, which puts us in a weird state (it's not actually a race condition, I don't know why I wrote that, I'll change the title; had a brain fart).

**Comment by ddymko** [comment]
The problem is with the API (large portion at least)...when you create a record we do not get back the ID of that record. To get the ID of that record we then need to make a list call and loop through all the records and find the one we just created.

If the ratelimit gets hit during the list call and fails to retrieve the list of Records we then get stuck in a state where the record was created but we could not set its ID.

https://github.com/terraform-providers/terraform-provider-vultr/blob/36aead8542a0dd18a4741611b562ca7a70f35d2e/vultr/resource_vultr_dns_records.go#L79

Majority of the issues are due to the API v1 having very strange patterns/behavior which is why we are working on V2 right now to cleanup/modernize.

**Comment by SamWhited** [comment]
I see, that makes sense, so you'd have to actually loop again (after already hitting the rate limit) before you could even save it to the terraform state. Thanks for your help.

**Comment by ddymko** [comment]
Correct - this and other behavior the current API has is why we are working on a V2 right now.
