### ISSUE TITLE
DNS functionality should retry API calls

### ISSUE THREAD

**Issue by iggy** [vultr/terraform-provider-vultr#50]
I'm not sure if this is a matter of vultr's DNS API being eventually consistent or what, but I'm having a hell of a time doing anything meaningful with the vultr provider and DNS.

If I create a new domain with some records, the new domain creates, but terraform then complains it can't add the DNS records and exits.

```
Error: Error creating DNS record : Invalid domain.  Check domain value and ensure your API key matches the domains's account

  on modules/gmail_mx/main.tf line 10, in resource "vultr_dns_record" "vultr_gmail_alt1":
  10: resource "vultr_dns_record" "vultr_gmail_alt1" {
```
If I then immediately retry the apply, it finds the domain and creates the records (in Vultr, not in the terraform state) but fails with the following error. It's like it creates, but before the database/API is updated it queries and gets no records back.
```
Error: Error finding DNS record: <nil>

  on modules/gmail_mx/main.tf line 10, in resource "vultr_dns_record" "vultr_gmail_alt1":
  10: resource "vultr_dns_record" "vultr_gmail_alt1" {
```
If I then rerun the apply, I get the following error, which is correct because it did create the records, they just didn't make it into the tf state.
```
Error: Error creating DNS record : Unable to add record: Duplicate records are not allowed.

  on modules/gmail_mx/main.tf line 10, in resource "vultr_dns_record" "vultr_gmail_alt1":
  10: resource "vultr_dns_record" "vultr_gmail_alt1" {
```
This almost seems like it needs some sort of retry logic to check a few more times if the first call fails.

If you need any more info from me, let me know.

**Comment by ddymko** [comment]
@iggy There already is retry logic in place 
https://www.terraform.io/docs/providers/vultr/index.html#argument-reference

The issue is similar to what is described here:
https://github.com/terraform-providers/terraform-provider-vultr/issues/44#issuecomment-637559740
https://github.com/terraform-providers/terraform-provider-vultr/issues/44#issuecomment-637567868

We first create the record but the API does not return the `Record-id` so we then have to make a second call to retrieve the list of records and loop through them to find it.

https://github.com/terraform-providers/terraform-provider-vultr/blob/2283825f55fbd665774606dcf742cd58b350262d/vultr/resource_vultr_dns_records.go#L72

Like I mentioned in the other tickets API V1 has a lot of pain points that keep me up at night. That's why V2 is in currently in development to fix all of these, very strange, design choices.
